// Date: 16-06-2013 21:56:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package me.jacobschwartz.gunMod;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBullet extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape32;
    ModelRenderer Shape22;
    ModelRenderer Shape12;
  
  public ModelBullet()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 10, 1);
      Shape1.addBox(0F, -1.5F, 0F, 6, 3, 0);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(32, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 7, 11);
      Shape2.addBox(0F, 0F, -1.5F, 6, 0, 3);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(32, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 1, 13);
      Shape3.addBox(0F, -1.5F, -1.5F, 0, 3, 3);
      Shape3.setRotationPoint(0F, 0F, 0F);
      Shape3.setTextureSize(32, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape32 = new ModelRenderer(this, 1, 13);
      Shape32.addBox(0F, -1.5F, -1.5F, 0, 3, 3);
      Shape32.setRotationPoint(0F, 0F, 0F);
      Shape32.setTextureSize(32, 32);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 3.141593F, 0F);
      Shape22 = new ModelRenderer(this, 7, 11);
      Shape22.addBox(0F, 0F, -1.5F, 6, 0, 3);
      Shape22.setRotationPoint(0F, 0F, 0F);
      Shape22.setTextureSize(32, 32);
      Shape22.mirror = true;
      setRotation(Shape22, 3.141593F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 10, 1);
      Shape12.addBox(0F, -1.5F, 0F, 6, 3, 0);
      Shape12.setRotationPoint(0F, 0F, 0F);
      Shape12.setTextureSize(32, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 3.141593F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float scale)
  {
    super.render(entity, f, f1, f2, f3, f4, scale);
    setRotationAngles(f, f1, f2, f3, f4, scale, entity);
    Shape1.render(scale);
    Shape2.render(scale);
    Shape3.render(scale);
    Shape32.render(scale);
    Shape22.render(scale);
    Shape12.render(scale);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
